#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AL_Cage

#include "Basic.hpp"

#include "ThankYouVeryCool_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass AL_Cage.AL_Cage_C
// 0x0000 (0x0100 - 0x0100)
class UAL_Cage_C final : public UArcadeLevelAsset
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AL_Cage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AL_Cage_C")
	}
	static class UAL_Cage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAL_Cage_C>();
	}
};
DUMPER7_ASSERTS_UAL_Cage_C;

SDK_NAMESPACE_END
