#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CampaignTriggerVolume

#include "Basic.hpp"

#include "ThankYouVeryCool_structs.hpp"
#include "ThankYouVeryCool_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CampaignTriggerVolume.BP_CampaignTriggerVolume_C
// 0x0018 (0x02D0 - 0x02B8)
class ABP_CampaignTriggerVolume_C final : public ACampaignTriggerVolume
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_TargetIndicatorComponent_C*         BP_TargetIndicatorComponent;                       // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNavModifierComponent*                  NavBlocker;                                        // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_CampaignTriggerVolume(int32 EntryPoint);
	void DoActions(EActionType ToDo, bool bSimulated);
	void SetNavBlocking(bool bNavBlocking);
	void PostDataLoaded();
	void ReceiveDestroyed();
	void RequestInteraction(class AActor* Interactor);
	bool IsInteractable();
	class FText GetInteractionText();
	TArray<EGoalType> GetGoals();
	TArray<EActionType> GetActions();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CampaignTriggerVolume_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CampaignTriggerVolume_C")
	}
	static class ABP_CampaignTriggerVolume_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CampaignTriggerVolume_C>();
	}
};
DUMPER7_ASSERTS_ABP_CampaignTriggerVolume_C;

SDK_NAMESPACE_END
