#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CustomChameleon

#include "Basic.hpp"

#include "BP_CustomChameleon_classes.hpp"
#include "BP_CustomChameleon_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_CustomChameleon.BP_CustomChameleon_C.ExecuteUbergraph_BP_CustomChameleon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CustomChameleon_C::ExecuteUbergraph_BP_CustomChameleon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "ExecuteUbergraph_BP_CustomChameleon");

	Params::BP_CustomChameleon_C_ExecuteUbergraph_BP_CustomChameleon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CustomChameleon_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.LerpFadeIn
// (Event, Public, BlueprintEvent)

void ABP_CustomChameleon_C::LerpFadeIn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "LerpFadeIn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.LerpFadeOut
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   SpeedModifier                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CustomChameleon_C::LerpFadeOut(float SpeedModifier)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "LerpFadeOut");

	Params::BP_CustomChameleon_C_LerpFadeOut Parms{};

	Parms.SpeedModifier = SpeedModifier;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.DoHeadshot
// (Event, Public, BlueprintEvent)
// Parameters:
// const struct FVector&                   HeadshotLocation                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CustomChameleon_C::DoHeadshot(const struct FVector& HeadshotLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "DoHeadshot");

	Params::BP_CustomChameleon_C_DoHeadshot Parms{};

	Parms.HeadshotLocation = std::move(HeadshotLocation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.FadeToBW
// (Event, Public, BlueprintEvent)

void ABP_CustomChameleon_C::FadeToBW()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "FadeToBW");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.SetBlinkHalfOpen
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bOpen                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_CustomChameleon_C::SetBlinkHalfOpen(bool bOpen)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "SetBlinkHalfOpen");

	Params::BP_CustomChameleon_C_SetBlinkHalfOpen Parms{};

	Parms.bOpen = bOpen;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.DoHitEffect
// (Event, Public, BlueprintEvent)

void ABP_CustomChameleon_C::DoHitEffect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "DoHitEffect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.DoBlink
// (Event, Public, BlueprintEvent)

void ABP_CustomChameleon_C::DoBlink()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "DoBlink");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.LerpFadeInToReset
// (Event, Public, BlueprintEvent)

void ABP_CustomChameleon_C::LerpFadeInToReset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "LerpFadeInToReset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.LerpFadeOutToReset
// (Event, Public, BlueprintEvent)

void ABP_CustomChameleon_C::LerpFadeOutToReset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "LerpFadeOutToReset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.LerpFadeOutToChallenges
// (Event, Public, BlueprintEvent)

void ABP_CustomChameleon_C::LerpFadeOutToChallenges()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "LerpFadeOutToChallenges");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.LerpFadeInToChallenges
// (Event, Public, BlueprintEvent)

void ABP_CustomChameleon_C::LerpFadeInToChallenges()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "LerpFadeInToChallenges");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.LerpFadeInFromLoad
// (Event, Public, BlueprintEvent)

void ABP_CustomChameleon_C::LerpFadeInFromLoad()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "LerpFadeInFromLoad");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.LerpFadeOutToLoad
// (Event, Public, BlueprintEvent)

void ABP_CustomChameleon_C::LerpFadeOutToLoad()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "LerpFadeOutToLoad");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.LerpFadeOutTimeline__UpdateFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::LerpFadeOutTimeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "LerpFadeOutTimeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.LerpFadeOutTimeline__FinishedFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::LerpFadeOutTimeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "LerpFadeOutTimeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.HeadshotTimeline__UpdateFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::HeadshotTimeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "HeadshotTimeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.HeadshotTimeline__FinishedFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::HeadshotTimeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "HeadshotTimeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.BWTimeline__UpdateFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::BWTimeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "BWTimeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.BWTimeline__FinishedFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::BWTimeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "BWTimeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_8__UpdateFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_8__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_8__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_8__FinishedFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_8__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_8__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Blur__UpdateFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Blur__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Blur__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Blur__FinishedFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Blur__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Blur__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_7__UpdateFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_7__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_7__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_7__FinishedFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_7__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_7__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_6__UpdateFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_6__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_6__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_6__FinishedFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_6__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_6__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_5__UpdateFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_5__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_5__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_5__FinishedFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_5__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_5__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_4__UpdateFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_4__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_4__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_4__FinishedFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_4__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_4__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_3__UpdateFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_3__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_3__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_3__FinishedFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_3__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_3__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_2__UpdateFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_2__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_2__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomChameleon.BP_CustomChameleon_C.Timeline_2__FinishedFunc
// (BlueprintEvent)

void ABP_CustomChameleon_C::Timeline_2__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomChameleon_C", "Timeline_2__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
