#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GlassSpawner

#include "Basic.hpp"

#include "Voxel_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GlassSpawner.BP_GlassSpawner_C
// 0x0000 (0x0048 - 0x0048)
class UBP_GlassSpawner_C final : public UVoxelPhysicsPartSpawner_Cubes
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GlassSpawner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GlassSpawner_C")
	}
	static class UBP_GlassSpawner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GlassSpawner_C>();
	}
};
DUMPER7_ASSERTS_UBP_GlassSpawner_C;

SDK_NAMESPACE_END
