#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PoolableFIre

#include "Basic.hpp"

#include "ThankYouVeryCool_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PoolableFIre.BP_PoolableFIre_C
// 0x0018 (0x02A0 - 0x0288)
class ABP_PoolableFIre_C final : public APoolableFire
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0288(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAudioComponent*                        Audio;                                             // 0x0290(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               ParticleSystem;                                    // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_PoolableFIre(int32 EntryPoint);
	void StartBurning();
	void MakeDormantBP();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PoolableFIre_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PoolableFIre_C")
	}
	static class ABP_PoolableFIre_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PoolableFIre_C>();
	}
};
DUMPER7_ASSERTS_ABP_PoolableFIre_C;

SDK_NAMESPACE_END
