#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Pillow

#include "Basic.hpp"

#include "BP_PropVoxelWorld_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Pillow.BP_Pillow_C
// 0x0000 (0x0AB0 - 0x0AB0)
class ABP_Pillow_C final : public ABP_PropVoxelWorld_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Pillow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Pillow_C")
	}
	static class ABP_Pillow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Pillow_C>();
	}
};
DUMPER7_ASSERTS_ABP_Pillow_C;

SDK_NAMESPACE_END
