#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Quad_Mini

#include "Basic.hpp"

#include "BP_Quad_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Quad_Mini.BP_Quad_Mini_C
// 0x0000 (0x06B0 - 0x06B0)
class ABP_Quad_Mini_C final : public ABP_Quad_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Quad_Mini_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Quad_Mini_C")
	}
	static class ABP_Quad_Mini_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Quad_Mini_C>();
	}
};
DUMPER7_ASSERTS_ABP_Quad_Mini_C;

SDK_NAMESPACE_END
