#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StatsManager

#include "Basic.hpp"

#include "BP_StatsManager_classes.hpp"
#include "BP_StatsManager_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_StatsManager.BP_StatsManager_C.ExecuteUbergraph_BP_StatsManager
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StatsManager_C::ExecuteUbergraph_BP_StatsManager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "ExecuteUbergraph_BP_StatsManager");

	Params::BP_StatsManager_C_ExecuteUbergraph_BP_StatsManager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StatsManager.BP_StatsManager_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_StatsManager_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.DoFFLevelCheevs
// (BlueprintCallable, BlueprintEvent)

void ABP_StatsManager_C::DoFFLevelCheevs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "DoFFLevelCheevs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.UpdateCheevos
// (Event, Public, BlueprintEvent)

void ABP_StatsManager_C::UpdateCheevos()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "UpdateCheevos");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.GiveCheevosOthers
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const TArray<class FName>&              ToGive                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_StatsManager_C::GiveCheevosOthers(const TArray<class FName>& ToGive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "GiveCheevosOthers");

	Params::BP_StatsManager_C_GiveCheevosOthers Parms{};

	Parms.ToGive = std::move(ToGive);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StatsManager.BP_StatsManager_C.Loggedin
// (BlueprintCallable, BlueprintEvent)

void ABP_StatsManager_C::Loggedin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "Loggedin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.LoginToOSS
// (Event, Public, BlueprintEvent)

void ABP_StatsManager_C::LoginToOSS()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "LoginToOSS");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.DoChallengeComplete
// (Event, Public, BlueprintEvent)

void ABP_StatsManager_C::DoChallengeComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "DoChallengeComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.GiveCheevoOthers
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             ToGive                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StatsManager_C::GiveCheevoOthers(class FName ToGive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "GiveCheevoOthers");

	Params::BP_StatsManager_C_GiveCheevoOthers Parms{};

	Parms.ToGive = ToGive;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StatsManager.BP_StatsManager_C.OnSuccess_3E661B694B60688E96F66F99D6EE541E
// (BlueprintCallable, BlueprintEvent)

void ABP_StatsManager_C::OnSuccess_3E661B694B60688E96F66F99D6EE541E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnSuccess_3E661B694B60688E96F66F99D6EE541E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.OnFailure_3E661B694B60688E96F66F99D6EE541E
// (BlueprintCallable, BlueprintEvent)

void ABP_StatsManager_C::OnFailure_3E661B694B60688E96F66F99D6EE541E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnFailure_3E661B694B60688E96F66F99D6EE541E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.OnSuccess_F527A34C4A39B34136E2199382A7F175
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             WrittenAchievementName                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   WrittenProgress                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   WrittenUserTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StatsManager_C::OnSuccess_F527A34C4A39B34136E2199382A7F175(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnSuccess_F527A34C4A39B34136E2199382A7F175");

	Params::BP_StatsManager_C_OnSuccess_F527A34C4A39B34136E2199382A7F175 Parms{};

	Parms.WrittenAchievementName = WrittenAchievementName;
	Parms.WrittenProgress = WrittenProgress;
	Parms.WrittenUserTag = WrittenUserTag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StatsManager.BP_StatsManager_C.OnFailure_F527A34C4A39B34136E2199382A7F175
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             WrittenAchievementName                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   WrittenProgress                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   WrittenUserTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StatsManager_C::OnFailure_F527A34C4A39B34136E2199382A7F175(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnFailure_F527A34C4A39B34136E2199382A7F175");

	Params::BP_StatsManager_C_OnFailure_F527A34C4A39B34136E2199382A7F175 Parms{};

	Parms.WrittenAchievementName = WrittenAchievementName;
	Parms.WrittenProgress = WrittenProgress;
	Parms.WrittenUserTag = WrittenUserTag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StatsManager.BP_StatsManager_C.OnSuccess_D7920D3B4A9B4F25BFABF1AE482C4E07
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StatsManager_C::OnSuccess_D7920D3B4A9B4F25BFABF1AE482C4E07(class APlayerController* PlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnSuccess_D7920D3B4A9B4F25BFABF1AE482C4E07");

	Params::BP_StatsManager_C_OnSuccess_D7920D3B4A9B4F25BFABF1AE482C4E07 Parms{};

	Parms.PlayerController = PlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StatsManager.BP_StatsManager_C.OnFailure_D7920D3B4A9B4F25BFABF1AE482C4E07
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StatsManager_C::OnFailure_D7920D3B4A9B4F25BFABF1AE482C4E07(class APlayerController* PlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnFailure_D7920D3B4A9B4F25BFABF1AE482C4E07");

	Params::BP_StatsManager_C_OnFailure_D7920D3B4A9B4F25BFABF1AE482C4E07 Parms{};

	Parms.PlayerController = PlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StatsManager.BP_StatsManager_C.OnSuccess_4F4346CA441716B6384BF381B8C01FCB
// (BlueprintCallable, BlueprintEvent)

void ABP_StatsManager_C::OnSuccess_4F4346CA441716B6384BF381B8C01FCB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnSuccess_4F4346CA441716B6384BF381B8C01FCB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.OnFailure_4F4346CA441716B6384BF381B8C01FCB
// (BlueprintCallable, BlueprintEvent)

void ABP_StatsManager_C::OnFailure_4F4346CA441716B6384BF381B8C01FCB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnFailure_4F4346CA441716B6384BF381B8C01FCB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.OnSuccess_4647F1E842B5E39A9B6A09B35C86F44F
// (BlueprintCallable, BlueprintEvent)

void ABP_StatsManager_C::OnSuccess_4647F1E842B5E39A9B6A09B35C86F44F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnSuccess_4647F1E842B5E39A9B6A09B35C86F44F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.OnFailure_4647F1E842B5E39A9B6A09B35C86F44F
// (BlueprintCallable, BlueprintEvent)

void ABP_StatsManager_C::OnFailure_4647F1E842B5E39A9B6A09B35C86F44F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnFailure_4647F1E842B5E39A9B6A09B35C86F44F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.OnSuccess_0F84230C4AE186253ED0C1AADF30CEC7
// (BlueprintCallable, BlueprintEvent)

void ABP_StatsManager_C::OnSuccess_0F84230C4AE186253ED0C1AADF30CEC7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnSuccess_0F84230C4AE186253ED0C1AADF30CEC7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.OnFailure_0F84230C4AE186253ED0C1AADF30CEC7
// (BlueprintCallable, BlueprintEvent)

void ABP_StatsManager_C::OnFailure_0F84230C4AE186253ED0C1AADF30CEC7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnFailure_0F84230C4AE186253ED0C1AADF30CEC7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.OnSuccess_A588EDD54F57475B69A7A7AA6329F5E7
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             WrittenAchievementName                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   WrittenProgress                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   WrittenUserTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StatsManager_C::OnSuccess_A588EDD54F57475B69A7A7AA6329F5E7(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnSuccess_A588EDD54F57475B69A7A7AA6329F5E7");

	Params::BP_StatsManager_C_OnSuccess_A588EDD54F57475B69A7A7AA6329F5E7 Parms{};

	Parms.WrittenAchievementName = WrittenAchievementName;
	Parms.WrittenProgress = WrittenProgress;
	Parms.WrittenUserTag = WrittenUserTag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StatsManager.BP_StatsManager_C.OnFailure_A588EDD54F57475B69A7A7AA6329F5E7
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             WrittenAchievementName                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   WrittenProgress                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   WrittenUserTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_StatsManager_C::OnFailure_A588EDD54F57475B69A7A7AA6329F5E7(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnFailure_A588EDD54F57475B69A7A7AA6329F5E7");

	Params::BP_StatsManager_C_OnFailure_A588EDD54F57475B69A7A7AA6329F5E7 Parms{};

	Parms.WrittenAchievementName = WrittenAchievementName;
	Parms.WrittenProgress = WrittenProgress;
	Parms.WrittenUserTag = WrittenUserTag;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StatsManager.BP_StatsManager_C.OnSuccess_F1501BCF42F72417C1BBD0A48334697C
// (BlueprintCallable, BlueprintEvent)

void ABP_StatsManager_C::OnSuccess_F1501BCF42F72417C1BBD0A48334697C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnSuccess_F1501BCF42F72417C1BBD0A48334697C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.OnFailure_F1501BCF42F72417C1BBD0A48334697C
// (BlueprintCallable, BlueprintEvent)

void ABP_StatsManager_C::OnFailure_F1501BCF42F72417C1BBD0A48334697C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "OnFailure_F1501BCF42F72417C1BBD0A48334697C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_StatsManager.BP_StatsManager_C.GetColorForRank
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InRank                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor ABP_StatsManager_C::GetColorForRank(int32 InRank)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "GetColorForRank");

	Params::BP_StatsManager_C_GetColorForRank Parms{};

	Parms.InRank = InRank;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_StatsManager.BP_StatsManager_C.GetTextForRank
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InRank                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText ABP_StatsManager_C::GetTextForRank(int32 InRank)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "GetTextForRank");

	Params::BP_StatsManager_C_GetTextForRank Parms{};

	Parms.InRank = InRank;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_StatsManager.BP_StatsManager_C.AddPlusToText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const class FText&                      In                                                     (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText*                            O                                                      (Parm, OutParm)

void ABP_StatsManager_C::AddPlusToText(const class FText& In, class FText* O)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatsManager_C", "AddPlusToText");

	Params::BP_StatsManager_C_AddPlusToText Parms{};

	Parms.In = std::move(In);

	UObject::ProcessEvent(Func, &Parms);

	if (O != nullptr)
		*O = std::move(Parms.O);
}


SDK_NAMESPACE_END
