#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_TripleJump

#include "Basic.hpp"

#include "ThankYouVeryCool_structs.hpp"
#include "ThankYouVeryCool_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPC_TripleJump.BPC_TripleJump_C
// 0x0008 (0x0098 - 0x0090)
class UBPC_TripleJump_C final : public UCardData
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0090(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BPC_TripleJump(int32 EntryPoint);
	void OnFirstAdded();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_TripleJump_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_TripleJump_C")
	}
	static class UBPC_TripleJump_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_TripleJump_C>();
	}
};
DUMPER7_ASSERTS_UBPC_TripleJump_C;

SDK_NAMESPACE_END
