#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: cda_ENIGMA1

#include "Basic.hpp"

#include "ThankYouVeryCool_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass cda_ENIGMA1.cda_ENIGMA1_C
// 0x0000 (0x00A8 - 0x00A8)
class Ucda_ENIGMA1_C final : public UCampaignDataAsset
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("cda_ENIGMA1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"cda_ENIGMA1_C")
	}
	static class Ucda_ENIGMA1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Ucda_ENIGMA1_C>();
	}
};
DUMPER7_ASSERTS_Ucda_ENIGMA1_C;

SDK_NAMESPACE_END
