#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CDA_Trash

#include "Basic.hpp"

#include "ThankYouVeryCool_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CDA_Trash.CDA_Trash_C
// 0x0000 (0x00A8 - 0x00A8)
class UCDA_Trash_C final : public UCampaignDataAsset
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CDA_Trash_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CDA_Trash_C")
	}
	static class UCDA_Trash_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCDA_Trash_C>();
	}
};
DUMPER7_ASSERTS_UCDA_Trash_C;

SDK_NAMESPACE_END
