#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Glock

#include "Basic.hpp"

#include "ThankYouVeryCool_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Glock.Glock_C
// 0x0010 (0x06F0 - 0x06E0)
class AGlock_C final : public AWeaponBase
{
public:
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x06E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_AmmoInd_C*                          BP_AmmoInd;                                        // 0x06E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Glock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Glock_C")
	}
	static class AGlock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGlock_C>();
	}
};
DUMPER7_ASSERTS_AGlock_C;

SDK_NAMESPACE_END
