#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_CrosshairManager

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "E_ProgressBarType_structs.hpp"
#include "E_ProgressBars_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass I_CrosshairManager.I_CrosshairManager_C
// 0x0000 (0x0000 - 0x0000)
class II_CrosshairManager_C final
{
public:
	void RemoveCrosshair();
	void Recoil();
	void ActivateCrosshair(const struct FVector2D& Scale);
	void CrosshairReaction(bool IsMoving);
	void ZoomIn();
	void ZoomOut();
	void HitIndicator(const struct FLinearColor& Color);
	void UpdateProgressBar(E_ProgressBarType ProgressType, float Time, float Value, const struct FLinearColor& EmptyColor, const struct FLinearColor& FillColor, E_ProgressBars ProgressBarType);
	void RemoveProgressBar();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("I_CrosshairManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"I_CrosshairManager_C")
	}
	static class II_CrosshairManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<II_CrosshairManager_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_II_CrosshairManager_C;

SDK_NAMESPACE_END
