#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LaserRev

#include "Basic.hpp"

#include "ThankYouVeryCool_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass LaserRev.LaserRev_C
// 0x0010 (0x06F0 - 0x06E0)
class ALaserRev_C final : public AWeaponBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x06E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_AmmoInd_C*                          BP_AmmoInd1;                                       // 0x06E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_LaserRev(int32 EntryPoint);
	void Randomize();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LaserRev_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LaserRev_C")
	}
	static class ALaserRev_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALaserRev_C>();
	}
};
DUMPER7_ASSERTS_ALaserRev_C;

SDK_NAMESPACE_END
