#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PickupWeapon

#include "Basic.hpp"

#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PickupWeapon.PickupWeapon_C
// 0x0038 (0x00E0 - 0x00A8)
class UPickupWeapon_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FBlackboardKeySelector                 WeaponKey;                                         // 0x00B0(0x0028)(Edit, BlueprintVisible)
	class UAnimMontage*                           PickupAnimation;                                   // 0x00D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_PickupWeapon(int32 EntryPoint);
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PickupWeapon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PickupWeapon_C")
	}
	static class UPickupWeapon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPickupWeapon_C>();
	}
};
DUMPER7_ASSERTS_UPickupWeapon_C;

SDK_NAMESPACE_END
