#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PortalItemInterface

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function PortalItemInterface.PortalItemInterface_C.post_teleport
// 0x0008 (0x0008 - 0x0000)
struct PortalItemInterface_C_post_teleport final
{
public:
	class APortalBP_C*                            from_portal;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PortalItemInterface_C_post_teleport;

// Function PortalItemInterface.PortalItemInterface_C.pre_teleport
// 0x0008 (0x0008 - 0x0000)
struct PortalItemInterface_C_pre_teleport final
{
public:
	class APortalBP_C*                            from_portal;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PortalItemInterface_C_pre_teleport;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
