#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PVW_Painting16

#include "Basic.hpp"

#include "PVW_PaintingBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PVW_Painting16.PVW_Painting16_C
// 0x0000 (0x0AB0 - 0x0AB0)
class APVW_Painting16_C final : public APVW_PaintingBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PVW_Painting16_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PVW_Painting16_C")
	}
	static class APVW_Painting16_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APVW_Painting16_C>();
	}
};
DUMPER7_ASSERTS_APVW_Painting16_C;

SDK_NAMESPACE_END
