#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PVW_ExplosiveSmallPC

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function PVW_ExplosiveSmallPC.PVW_ExplosiveSmallPC_C.ExecuteUbergraph_PVW_ExplosiveSmallPC
// 0x0004 (0x0004 - 0x0000)
struct PVW_ExplosiveSmallPC_C_ExecuteUbergraph_PVW_ExplosiveSmallPC final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PVW_ExplosiveSmallPC_C_ExecuteUbergraph_PVW_ExplosiveSmallPC;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
