#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RecoilShake_Mp7

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass RecoilShake_Mp7.RecoilShake_Mp7_C
// 0x0000 (0x01B0 - 0x01B0)
class URecoilShake_Mp7_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RecoilShake_Mp7_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RecoilShake_Mp7_C")
	}
	static class URecoilShake_Mp7_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URecoilShake_Mp7_C>();
	}
};
DUMPER7_ASSERTS_URecoilShake_Mp7_C;

SDK_NAMESPACE_END
