#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SK_SMG11_X_Skeleton_AnimBlueprint

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "ThankYouVeryCool_classes.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass SK_SMG11_X_Skeleton_AnimBlueprint.SK_SMG11_X_Skeleton_AnimBlueprint_C
// 0x02F0 (0x05C0 - 0x02D0)
class USK_SMG11_X_Skeleton_AnimBlueprint_C final : public UGunAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02D8(0x0030)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0308(0x0048)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_1;                        // 0x0350(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x0458(0x0108)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0560(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x0580(0x0020)()
	struct FVector                                StockExtension;                                    // 0x05A0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               StockRotation;                                     // 0x05AC(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_SK_SMG11_X_Skeleton_AnimBlueprint(int32 EntryPoint);
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SK_SMG11_X_Skeleton_AnimBlueprint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SK_SMG11_X_Skeleton_AnimBlueprint_C")
	}
	static class USK_SMG11_X_Skeleton_AnimBlueprint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USK_SMG11_X_Skeleton_AnimBlueprint_C>();
	}
};
DUMPER7_ASSERTS_USK_SMG11_X_Skeleton_AnimBlueprint_C;

SDK_NAMESPACE_END
