#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_GiveTreeToAllMembers

#include "Basic.hpp"

#include "ST_GiveTreeToAllMembers_classes.hpp"
#include "ST_GiveTreeToAllMembers_parameters.hpp"


SDK_NAMESPACE_START

// Function ST_GiveTreeToAllMembers.ST_GiveTreeToAllMembers_C.ExecuteUbergraph_ST_GiveTreeToAllMembers
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UST_GiveTreeToAllMembers_C::ExecuteUbergraph_ST_GiveTreeToAllMembers(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ST_GiveTreeToAllMembers_C", "ExecuteUbergraph_ST_GiveTreeToAllMembers");

	Params::ST_GiveTreeToAllMembers_C_ExecuteUbergraph_ST_GiveTreeToAllMembers Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ST_GiveTreeToAllMembers.ST_GiveTreeToAllMembers_C.ReceiveExecute
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AActor*                           OwnerActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UST_GiveTreeToAllMembers_C::ReceiveExecute(class AActor* OwnerActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ST_GiveTreeToAllMembers_C", "ReceiveExecute");

	Params::ST_GiveTreeToAllMembers_C_ReceiveExecute Parms{};

	Parms.OwnerActor = OwnerActor;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
