#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PatchNotes

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PatchNotes.WBP_PatchNotes_C
// 0x0008 (0x0268 - 0x0260)
class UWBP_PatchNotes_C final : public UUserWidget
{
public:
	class UWBP_dISCORDPLZ_C*                      WBP_dISCORDPLZ_C_0;                                // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PatchNotes_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PatchNotes_C")
	}
	static class UWBP_PatchNotes_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PatchNotes_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PatchNotes_C;

SDK_NAMESPACE_END
