#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Tutorial

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_Tutorial.WBP_Tutorial_C.ExecuteUbergraph_WBP_Tutorial
// 0x0040 (0x0040 - 0x0000)
struct WBP_Tutorial_C_ExecuteUbergraph_WBP_Tutorial final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_Num;                                  // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_Total;                                // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0010(0x0018)()
	class FText                                   CallFunc_Conv_IntToText_ReturnValue_1;             // 0x0028(0x0018)()
};
DUMPER7_ASSERTS_WBP_Tutorial_C_ExecuteUbergraph_WBP_Tutorial;

// Function WBP_Tutorial.WBP_Tutorial_C.SetTotal
// 0x0004 (0x0004 - 0x0000)
struct WBP_Tutorial_C_SetTotal final
{
public:
	int32                                         Total;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Tutorial_C_SetTotal;

// Function WBP_Tutorial.WBP_Tutorial_C.SetCompleted
// 0x0004 (0x0004 - 0x0000)
struct WBP_Tutorial_C_SetCompleted final
{
public:
	int32                                         Num;                                               // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Tutorial_C_SetCompleted;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
