#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_LiftCallWidget

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_LiftCallWidget.WBP_LiftCallWidget_C
// 0x0018 (0x0278 - 0x0260)
class UWBP_LiftCallWidget_C final : public UUserWidget
{
public:
	class UButton*                                Button_0;                                          // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_26;                                          // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class URetainerBox*                           RetainerBox_0;                                     // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_LiftCallWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_LiftCallWidget_C")
	}
	static class UWBP_LiftCallWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_LiftCallWidget_C>();
	}
};
DUMPER7_ASSERTS_UWBP_LiftCallWidget_C;

SDK_NAMESPACE_END
