#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ArcadeProgress

#include "Basic.hpp"

#include "WBP_ArcadeProgress_classes.hpp"
#include "WBP_ArcadeProgress_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_ArcadeProgress.WBP_ArcadeProgress_C.ExecuteUbergraph_WBP_ArcadeProgress
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ArcadeProgress_C::ExecuteUbergraph_WBP_ArcadeProgress(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ArcadeProgress_C", "ExecuteUbergraph_WBP_ArcadeProgress");

	Params::WBP_ArcadeProgress_C_ExecuteUbergraph_WBP_ArcadeProgress Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ArcadeProgress.WBP_ArcadeProgress_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_ArcadeProgress_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ArcadeProgress_C", "PreConstruct");

	Params::WBP_ArcadeProgress_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ArcadeProgress.WBP_ArcadeProgress_C.OnInitialLoadComplete
// (BlueprintCallable, BlueprintEvent)

void UWBP_ArcadeProgress_C::OnInitialLoadComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ArcadeProgress_C", "OnInitialLoadComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ArcadeProgress.WBP_ArcadeProgress_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ArcadeProgress_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ArcadeProgress_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ArcadeProgress.WBP_ArcadeProgress_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ArcadeProgress_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ArcadeProgress_C", "Tick");

	Params::WBP_ArcadeProgress_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ArcadeProgress.WBP_ArcadeProgress_C.SetToXP
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   InXP                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ArcadeProgress_C::SetToXP(float InXP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ArcadeProgress_C", "SetToXP");

	Params::WBP_ArcadeProgress_C_SetToXP Parms{};

	Parms.InXP = InXP;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ArcadeProgress.WBP_ArcadeProgress_C.AnimateToXP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   StartXP                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   EndXP                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ArcadeProgress_C::AnimateToXP(int32 StartXP, int32 EndXP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ArcadeProgress_C", "AnimateToXP");

	Params::WBP_ArcadeProgress_C_AnimateToXP Parms{};

	Parms.StartXP = StartXP;
	Parms.EndXP = EndXP;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ArcadeProgress.WBP_ArcadeProgress_C.GetXPToProgress
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ProgressingFrom                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Needed                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ArcadeProgress_C::GetXPToProgress(int32 ProgressingFrom, int32* Needed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ArcadeProgress_C", "GetXPToProgress");

	Params::WBP_ArcadeProgress_C_GetXPToProgress Parms{};

	Parms.ProgressingFrom = ProgressingFrom;

	UObject::ProcessEvent(Func, &Parms);

	if (Needed != nullptr)
		*Needed = Parms.Needed;
}


// Function WBP_ArcadeProgress.WBP_ArcadeProgress_C.Tick Progress
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_ArcadeProgress_C::Tick_Progress()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ArcadeProgress_C", "Tick Progress");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ArcadeProgress.WBP_ArcadeProgress_C.AnimateV2
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   End                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ArcadeProgress_C::AnimateV2(int32 Start, int32 End)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ArcadeProgress_C", "AnimateV2");

	Params::WBP_ArcadeProgress_C_AnimateV2 Parms{};

	Parms.Start = Start;
	Parms.End = End;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
