#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Eden01

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_Eden01.WBP_Eden01_C.ExecuteUbergraph_WBP_Eden01
// 0x000C (0x000C - 0x0000)
struct WBP_Eden01_C_ExecuteUbergraph_WBP_Eden01 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_InLevel;                        // 0x0004(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Eden01_C_ExecuteUbergraph_WBP_Eden01;

// Function WBP_Eden01.WBP_Eden01_C.SnapToLevel
// 0x0008 (0x0008 - 0x0000)
struct WBP_Eden01_C_SnapToLevel final
{
public:
	class FName                                   InLevel;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Eden01_C_SnapToLevel;

// Function WBP_Eden01.WBP_Eden01_C.LerpToLevel
// 0x0008 (0x0008 - 0x0000)
struct WBP_Eden01_C_LerpToLevel final
{
public:
	class FName                                   ToLerpTo;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Eden01_C_LerpToLevel;

// Function WBP_Eden01.WBP_Eden01_C.EnsureReady
// 0x0050 (0x0050 - 0x0000)
struct WBP_Eden01_C_EnsureReady final
{
public:
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0000(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Eden01Map_C*                        CallFunc_FinishSpawningActor_ReturnValue;          // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Eden01_C_EnsureReady;

// Function WBP_Eden01.WBP_Eden01_C.CleanUp
// 0x0001 (0x0001 - 0x0000)
struct WBP_Eden01_C_CleanUp final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_Eden01_C_CleanUp;

// Function WBP_Eden01.WBP_Eden01_C.SnapThenLerp
// 0x0010 (0x0010 - 0x0000)
struct WBP_Eden01_C_SnapThenLerp final
{
public:
	class FName                                   Start;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   End;                                               // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Eden01_C_SnapThenLerp;

// Function WBP_Eden01.WBP_Eden01_C.ShutDown
// 0x0001 (0x0001 - 0x0000)
struct WBP_Eden01_C_ShutDown final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_Eden01_C_ShutDown;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
