#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AdamCrosshair

#include "Basic.hpp"

#include "WBP_AdamCrosshair_classes.hpp"
#include "WBP_AdamCrosshair_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_AdamCrosshair.WBP_AdamCrosshair_C.ExecuteUbergraph_WBP_AdamCrosshair
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_AdamCrosshair_C::ExecuteUbergraph_WBP_AdamCrosshair(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AdamCrosshair_C", "ExecuteUbergraph_WBP_AdamCrosshair");

	Params::WBP_AdamCrosshair_C_ExecuteUbergraph_WBP_AdamCrosshair Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_AdamCrosshair.WBP_AdamCrosshair_C.DoHitFlare
// (Event, Public, BlueprintEvent)

void UWBP_AdamCrosshair_C::DoHitFlare()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AdamCrosshair_C", "DoHitFlare");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_AdamCrosshair.WBP_AdamCrosshair_C.SetMyXHair
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_AdamCrosshair_C::SetMyXHair(class UTexture2D* NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AdamCrosshair_C", "SetMyXHair");

	Params::WBP_AdamCrosshair_C_SetMyXHair Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_AdamCrosshair.WBP_AdamCrosshair_C.GetColorAndOpacity_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UWBP_AdamCrosshair_C::GetColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AdamCrosshair_C", "GetColorAndOpacity_0");

	Params::WBP_AdamCrosshair_C_GetColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
