#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MainMenuV3

#include "Basic.hpp"

#include "WBP_MainMenuV3_classes.hpp"
#include "WBP_MainMenuV3_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ExecuteUbergraph_WBP_MainMenuV3
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenuV3_C::ExecuteUbergraph_WBP_MainMenuV3(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ExecuteUbergraph_WBP_MainMenuV3");

	Params::WBP_MainMenuV3_C_ExecuteUbergraph_WBP_MainMenuV3 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.DailyDiffSelected
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EDifficulty                             NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenuV3_C::DailyDiffSelected(EDifficulty NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "DailyDiffSelected");

	Params::WBP_MainMenuV3_C_DailyDiffSelected Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.canr
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::canr()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "canr");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.cr
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::cr()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "cr");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ShowRogueScreen
// (Event, Public, BlueprintEvent)

void UWBP_MainMenuV3_C::ShowRogueScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ShowRogueScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__WBP_MainMenuV3_RougueButton_K2Node_ComponentBoundEvent_31_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__WBP_MainMenuV3_RougueButton_K2Node_ComponentBoundEvent_31_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__WBP_MainMenuV3_RougueButton_K2Node_ComponentBoundEvent_31_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnPS5ActivityReturnToCampaign
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::OnPS5ActivityReturnToCampaign()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnPS5ActivityReturnToCampaign");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnPS5ActivityCampaignQuitToMainMenu
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::OnPS5ActivityCampaignQuitToMainMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnPS5ActivityCampaignQuitToMainMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnPS5ActivityReturnToLevelSelect
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::OnPS5ActivityReturnToLevelSelect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnPS5ActivityReturnToLevelSelect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnPS5ActivityArcadeQuitToMainMenu
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::OnPS5ActivityArcadeQuitToMainMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnPS5ActivityArcadeQuitToMainMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnStopCheckingPS5ActivityLaunchRequests
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::OnStopCheckingPS5ActivityLaunchRequests()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnStopCheckingPS5ActivityLaunchRequests");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnPS5CampaignLaunchRequested
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::OnPS5CampaignLaunchRequested()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnPS5CampaignLaunchRequested");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_MainMenuV3_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnStartCheckingPS5ActivityLaunchRequests
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::OnStartCheckingPS5ActivityLaunchRequests()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnStartCheckingPS5ActivityLaunchRequests");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnFinishPreGame
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::OnFinishPreGame()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnFinishPreGame");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__WBP_MainMenuV3_WBP_CheatCode_UnlockAll_K2Node_ComponentBoundEvent_34_OnCheatCodeComplete__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__WBP_MainMenuV3_WBP_CheatCode_UnlockAll_K2Node_ComponentBoundEvent_34_OnCheatCodeComplete__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__WBP_MainMenuV3_WBP_CheatCode_UnlockAll_K2Node_ComponentBoundEvent_34_OnCheatCodeComplete__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__WBP_MainMenuV3_WBP_CheatCode_K2Node_ComponentBoundEvent_33_OnCheatCodeComplete__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__WBP_MainMenuV3_WBP_CheatCode_K2Node_ComponentBoundEvent_33_OnCheatCodeComplete__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__WBP_MainMenuV3_WBP_CheatCode_K2Node_ComponentBoundEvent_33_OnCheatCodeComplete__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnInitialLoadComplete
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::OnInitialLoadComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnInitialLoadComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_MainMenuV3_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "PreConstruct");

	Params::WBP_MainMenuV3_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.DoneWithEp
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::DoneWithEp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "DoneWithEp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__WBP_MainMenuV3_WBP_AdamButton_619_K2Node_ComponentBoundEvent_32_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__WBP_MainMenuV3_WBP_AdamButton_619_K2Node_ComponentBoundEvent_32_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__WBP_MainMenuV3_WBP_AdamButton_619_K2Node_ComponentBoundEvent_32_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__WBP_MainMenuV3_WBP_AdamButton_490_K2Node_ComponentBoundEvent_30_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__WBP_MainMenuV3_WBP_AdamButton_490_K2Node_ComponentBoundEvent_30_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__WBP_MainMenuV3_WBP_AdamButton_490_K2Node_ComponentBoundEvent_30_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.DoEndGameCredits
// (Event, Public, BlueprintEvent)

void UWBP_MainMenuV3_C::DoEndGameCredits()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "DoEndGameCredits");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.SHOWCREDITS
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::SHOWCREDITS()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "SHOWCREDITS");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__WBP_MainMenuV3_WBP_AdamButton_152_K2Node_ComponentBoundEvent_29_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__WBP_MainMenuV3_WBP_AdamButton_152_K2Node_ComponentBoundEvent_29_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__WBP_MainMenuV3_WBP_AdamButton_152_K2Node_ComponentBoundEvent_29_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.PlayVideos
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::PlayVideos()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "PlayVideos");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ShowCampaignLevelSelectScreen
// (Event, Public, BlueprintEvent)

void UWBP_MainMenuV3_C::ShowCampaignLevelSelectScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ShowCampaignLevelSelectScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ZoomOutPlayVid
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::ZoomOutPlayVid()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ZoomOutPlayVid");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.CustomEvent_3
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::CustomEvent_3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "CustomEvent_3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.SetMenuVidSlow
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsSlow                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_MainMenuV3_C::SetMenuVidSlow(bool bIsSlow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "SetMenuVidSlow");

	Params::WBP_MainMenuV3_C_SetMenuVidSlow Parms{};

	Parms.bIsSlow = bIsSlow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.pLAYmENUvIDEOS
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::pLAYmENUvIDEOS()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "pLAYmENUvIDEOS");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__WBP_MainMenuV3_WBP_BottomBar_K2Node_ComponentBoundEvent_28_BackPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__WBP_MainMenuV3_WBP_BottomBar_K2Node_ComponentBoundEvent_28_BackPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__WBP_MainMenuV3_WBP_BottomBar_K2Node_ComponentBoundEvent_28_BackPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BackRequested_Event_0
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::BackRequested_Event_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BackRequested_Event_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__WBP_MainMenuV3_WBP_AdamButton_K2Node_ComponentBoundEvent_26_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__WBP_MainMenuV3_WBP_AdamButton_K2Node_ComponentBoundEvent_26_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__WBP_MainMenuV3_WBP_AdamButton_K2Node_ComponentBoundEvent_26_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__WBP_MainMenuV3_NOTARCADEBTN_K2Node_ComponentBoundEvent_14_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__WBP_MainMenuV3_NOTARCADEBTN_K2Node_ComponentBoundEvent_14_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__WBP_MainMenuV3_NOTARCADEBTN_K2Node_ComponentBoundEvent_14_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnLocSwap
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    NewLoc                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_MainMenuV3_C::OnLocSwap(const class FString& NewLoc)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnLocSwap");

	Params::WBP_MainMenuV3_C_OnLocSwap Parms{};

	Parms.NewLoc = std::move(NewLoc);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__WBP_MainMenuV3_WBP_MainCampaign_K2Node_ComponentBoundEvent_27_BackCalled__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__WBP_MainMenuV3_WBP_MainCampaign_K2Node_ComponentBoundEvent_27_BackCalled__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__WBP_MainMenuV3_WBP_MainCampaign_K2Node_ComponentBoundEvent_27_BackCalled__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.CustomEvent_2
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::CustomEvent_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "CustomEvent_2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.CustomEvent_1
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::CustomEvent_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "CustomEvent_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.DoPreGame
// (Event, Public, BlueprintEvent)

void UWBP_MainMenuV3_C::DoPreGame()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "DoPreGame");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.StopVideos
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::StopVideos()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "StopVideos");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ShowThisVictoryWidget
// (Event, Public, BlueprintEvent)
// Parameters:
// class UUserWidget*                      InWidget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenuV3_C::ShowThisVictoryWidget(class UUserWidget* InWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ShowThisVictoryWidget");

	Params::WBP_MainMenuV3_C_ShowThisVictoryWidget Parms{};

	Parms.InWidget = InWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ShowArcadeScreen
// (Event, Public, BlueprintEvent)

void UWBP_MainMenuV3_C::ShowArcadeScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ShowArcadeScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.HideEditor
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsController                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_MainMenuV3_C::HideEditor(bool bIsController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "HideEditor");

	Params::WBP_MainMenuV3_C_HideEditor Parms{};

	Parms.bIsController = bIsController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.CustomEvent_0
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::CustomEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "CustomEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__EditorButton_K2Node_ComponentBoundEvent_25_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__EditorButton_K2Node_ComponentBoundEvent_25_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__EditorButton_K2Node_ComponentBoundEvent_25_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__GamepadControlsButton_K2Node_ComponentBoundEvent_24_OnFocused__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__GamepadControlsButton_K2Node_ComponentBoundEvent_24_OnFocused__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__GamepadControlsButton_K2Node_ComponentBoundEvent_24_OnFocused__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__MKBControlsButton_K2Node_ComponentBoundEvent_23_OnFocused__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__MKBControlsButton_K2Node_ComponentBoundEvent_23_OnFocused__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__MKBControlsButton_K2Node_ComponentBoundEvent_23_OnFocused__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ShowPause_BP
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::ShowPause_BP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ShowPause_BP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__GamepadControlsButton_K2Node_ComponentBoundEvent_22_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__GamepadControlsButton_K2Node_ComponentBoundEvent_22_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__GamepadControlsButton_K2Node_ComponentBoundEvent_22_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__MKBControlsButton_K2Node_ComponentBoundEvent_21_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__MKBControlsButton_K2Node_ComponentBoundEvent_21_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__MKBControlsButton_K2Node_ComponentBoundEvent_21_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__GraphicsButton_K2Node_ComponentBoundEvent_20_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__GraphicsButton_K2Node_ComponentBoundEvent_20_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__GraphicsButton_K2Node_ComponentBoundEvent_20_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__AudioButton_K2Node_ComponentBoundEvent_19_OnFocused__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__AudioButton_K2Node_ComponentBoundEvent_19_OnFocused__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__AudioButton_K2Node_ComponentBoundEvent_19_OnFocused__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__AudioButton_K2Node_ComponentBoundEvent_18_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__AudioButton_K2Node_ComponentBoundEvent_18_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__AudioButton_K2Node_ComponentBoundEvent_18_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__MainBck_K2Node_ComponentBoundEvent_17_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__MainBck_K2Node_ComponentBoundEvent_17_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__MainBck_K2Node_ComponentBoundEvent_17_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__Button_0_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__Button_0_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__Button_0_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnControllerSwap_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsController                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_MainMenuV3_C::OnControllerSwap_Event_0(bool bIsController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnControllerSwap_Event_0");

	Params::WBP_MainMenuV3_C_OnControllerSwap_Event_0 Parms{};

	Parms.bIsController = bIsController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__WBP_AdamButton_K2Node_ComponentBoundEvent_15_OnControllerSwapBind__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsController                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_MainMenuV3_C::BndEvt__WBP_AdamButton_K2Node_ComponentBoundEvent_15_OnControllerSwapBind__DelegateSignature(bool bIsController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__WBP_AdamButton_K2Node_ComponentBoundEvent_15_OnControllerSwapBind__DelegateSignature");

	Params::WBP_MainMenuV3_C_BndEvt__WBP_AdamButton_K2Node_ComponentBoundEvent_15_OnControllerSwapBind__DelegateSignature Parms{};

	Parms.bIsController = bIsController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ClosePauseScreen
// (Event, Public, BlueprintEvent)

void UWBP_MainMenuV3_C::ClosePauseScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ClosePauseScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ShowChallengeScreen
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::ShowChallengeScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ShowChallengeScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.FadeIn
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::FadeIn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "FadeIn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ShowPauseScreen
// (Event, Public, BlueprintEvent)

void UWBP_MainMenuV3_C::ShowPauseScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ShowPauseScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__CampaignButton_K2Node_ComponentBoundEvent_12_OnFocused__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__CampaignButton_K2Node_ComponentBoundEvent_12_OnFocused__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__CampaignButton_K2Node_ComponentBoundEvent_12_OnFocused__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.FadeOut
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::FadeOut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "FadeOut");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__CampaignButton_K2Node_ComponentBoundEvent_10_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__CampaignButton_K2Node_ComponentBoundEvent_10_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__CampaignButton_K2Node_ComponentBoundEvent_10_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__AmmoIndyOff_K2Node_ComponentBoundEvent_13_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__AmmoIndyOff_K2Node_ComponentBoundEvent_13_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__AmmoIndyOff_K2Node_ComponentBoundEvent_13_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__AmmoIndyOn_K2Node_ComponentBoundEvent_10_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__AmmoIndyOn_K2Node_ComponentBoundEvent_10_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__AmmoIndyOn_K2Node_ComponentBoundEvent_10_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__WhiteHUD_K2Node_ComponentBoundEvent_9_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__WhiteHUD_K2Node_ComponentBoundEvent_9_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__WhiteHUD_K2Node_ComponentBoundEvent_9_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__GreenHUD_K2Node_ComponentBoundEvent_8_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__GreenHUD_K2Node_ComponentBoundEvent_8_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__GreenHUD_K2Node_ComponentBoundEvent_8_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__BlueHUD_K2Node_ComponentBoundEvent_7_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__BlueHUD_K2Node_ComponentBoundEvent_7_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__BlueHUD_K2Node_ComponentBoundEvent_7_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__OrangeHUD_K2Node_ComponentBoundEvent_4_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__OrangeHUD_K2Node_ComponentBoundEvent_4_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__OrangeHUD_K2Node_ComponentBoundEvent_4_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__GameButton_K2Node_ComponentBoundEvent_6_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__GameButton_K2Node_ComponentBoundEvent_6_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__GameButton_K2Node_ComponentBoundEvent_6_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__GraphicsButton_K2Node_ComponentBoundEvent_5_OnFocused__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__GraphicsButton_K2Node_ComponentBoundEvent_5_OnFocused__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__GraphicsButton_K2Node_ComponentBoundEvent_5_OnFocused__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__GameButton_K2Node_ComponentBoundEvent_3_OnFocused__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__GameButton_K2Node_ComponentBoundEvent_3_OnFocused__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__GameButton_K2Node_ComponentBoundEvent_3_OnFocused__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__BackButton_K2Node_ComponentBoundEvent_2_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__BackButton_K2Node_ComponentBoundEvent_2_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__BackButton_K2Node_ComponentBoundEvent_2_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__SettingsButton_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__SettingsButton_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__SettingsButton_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.BndEvt__WBP_AdamButton_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_MainMenuV3_C::BndEvt__WBP_AdamButton_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "BndEvt__WBP_AdamButton_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_MainMenuV3_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnSuccess_1CF2DC8246F77202380D799EF9F7EA38
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::OnSuccess_1CF2DC8246F77202380D799EF9F7EA38()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnSuccess_1CF2DC8246F77202380D799EF9F7EA38");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnFailure_1CF2DC8246F77202380D799EF9F7EA38
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::OnFailure_1CF2DC8246F77202380D799EF9F7EA38()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnFailure_1CF2DC8246F77202380D799EF9F7EA38");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.GetDefaultFocus
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_MainMenuV3_C::GetDefaultFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "GetDefaultFocus");

	Params::WBP_MainMenuV3_C_GetDefaultFocus Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.Down to Ammo Indy
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_MainMenuV3_C::Down_to_Ammo_Indy(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "Down to Ammo Indy");

	Params::WBP_MainMenuV3_C_Down_to_Ammo_Indy Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnKeyDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_MainMenuV3_C::OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnKeyDown");

	Params::WBP_MainMenuV3_C_OnKeyDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.GoBack
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::GoBack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "GoBack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.GoToMain
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          GoToOverride                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenuV3_C::GoToMain(class UWidget* GoToOverride)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "GoToMain");

	Params::WBP_MainMenuV3_C_GoToMain Parms{};

	Parms.GoToOverride = GoToOverride;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.GoToSettings
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::GoToSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "GoToSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.GoToGameSettings
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::GoToGameSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "GoToGameSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.UpdateSettingDisplay
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::UpdateSettingDisplay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "UpdateSettingDisplay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.Up to HUDColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_MainMenuV3_C::Up_to_HUDColor(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "Up to HUDColor");

	Params::WBP_MainMenuV3_C_Up_to_HUDColor Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.GoToArcadeSetup
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::GoToArcadeSetup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "GoToArcadeSetup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnMouseMove
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_MainMenuV3_C::OnMouseMove(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnMouseMove");

	Params::WBP_MainMenuV3_C_OnMouseMove Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ButtonNotifyFocus
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          ToFocusOn                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenuV3_C::ButtonNotifyFocus(class UWidget* ToFocusOn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ButtonNotifyFocus");

	Params::WBP_MainMenuV3_C_ButtonNotifyFocus Parms{};

	Parms.ToFocusOn = ToFocusOn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.GoToCampaign
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::GoToCampaign()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "GoToCampaign");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.GetPauseDefaultFocus
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_MainMenuV3_C::GetPauseDefaultFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "GetPauseDefaultFocus");

	Params::WBP_MainMenuV3_C_GetPauseDefaultFocus Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ShowAudioSettings
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::ShowAudioSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ShowAudioSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ShowGraphicsSettings
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::ShowGraphicsSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ShowGraphicsSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.Show MKBControls
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::Show_MKBControls()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "Show MKBControls");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.ShowGamepadControls
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::ShowGamepadControls()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "ShowGamepadControls");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.GoToPauseSettings
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::GoToPauseSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "GoToPauseSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.UntoggleAllSettings
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::UntoggleAllSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "UntoggleAllSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.Focus on Exit
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_MainMenuV3_C::Focus_on_Exit(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "Focus on Exit");

	Params::WBP_MainMenuV3_C_Focus_on_Exit Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.To Lang
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_MainMenuV3_C::To_Lang(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "To Lang");

	Params::WBP_MainMenuV3_C_To_Lang Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.InGameDiffSelect
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::InGameDiffSelect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "InGameDiffSelect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnPostCreditMsgClosed
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::OnPostCreditMsgClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnPostCreditMsgClosed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.OnKeyUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_MainMenuV3_C::OnKeyUp(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "OnKeyUp");

	Params::WBP_MainMenuV3_C_OnKeyUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.GoToRogue
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::GoToRogue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "GoToRogue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.Focus on Rogue
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_MainMenuV3_C::Focus_on_Rogue(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "Focus on Rogue");

	Params::WBP_MainMenuV3_C_Focus_on_Rogue Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.Go to DailyPlay
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::Go_to_DailyPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "Go to DailyPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenuV3.WBP_MainMenuV3_C.GoToDailyLB
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenuV3_C::GoToDailyLB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenuV3_C", "GoToDailyLB");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
