#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SteamUploading

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_SteamUploading.WBP_SteamUploading_C
// 0x0000 (0x0260 - 0x0260)
class UWBP_SteamUploading_C final : public UUserWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SteamUploading_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SteamUploading_C")
	}
	static class UWBP_SteamUploading_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SteamUploading_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SteamUploading_C;

SDK_NAMESPACE_END
