#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GraphicsSettings

#include "Basic.hpp"

#include "WBP_GraphicsSettings_classes.hpp"
#include "WBP_GraphicsSettings_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.ExecuteUbergraph_WBP_GraphicsSettings
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GraphicsSettings_C::ExecuteUbergraph_WBP_GraphicsSettings(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "ExecuteUbergraph_WBP_GraphicsSettings");

	Params::WBP_GraphicsSettings_C_ExecuteUbergraph_WBP_GraphicsSettings Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.ResetGameSettings
// (BlueprintCallable, BlueprintEvent)

void UWBP_GraphicsSettings_C::ResetGameSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "ResetGameSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.CancelResetSettings
// (BlueprintCallable, BlueprintEvent)

void UWBP_GraphicsSettings_C::CancelResetSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "CancelResetSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_SettingsReset_K2Node_ComponentBoundEvent_35_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_SettingsReset_K2Node_ComponentBoundEvent_35_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_SettingsReset_K2Node_ComponentBoundEvent_35_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_FFX_K2Node_ComponentBoundEvent_34_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_FFX_K2Node_ComponentBoundEvent_34_OnSelectionChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_FFX_K2Node_ComponentBoundEvent_34_OnSelectionChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_unlimitedragdolls_1_K2Node_ComponentBoundEvent_33_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_unlimitedragdolls_1_K2Node_ComponentBoundEvent_33_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_unlimitedragdolls_1_K2Node_ComponentBoundEvent_33_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_FOVSlider_1_K2Node_ComponentBoundEvent_32_OnMouseCaptureEndEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_FOVSlider_1_K2Node_ComponentBoundEvent_32_OnMouseCaptureEndEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_FOVSlider_1_K2Node_ComponentBoundEvent_32_OnMouseCaptureEndEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_FOVSlider_1_K2Node_ComponentBoundEvent_31_OnControllerCaptureEndEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_FOVSlider_1_K2Node_ComponentBoundEvent_31_OnControllerCaptureEndEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_FOVSlider_1_K2Node_ComponentBoundEvent_31_OnControllerCaptureEndEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_FOVSlider_1_K2Node_ComponentBoundEvent_30_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_FOVSlider_1_K2Node_ComponentBoundEvent_30_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_FOVSlider_1_K2Node_ComponentBoundEvent_30_OnFloatValueChangedEvent__DelegateSignature");

	Params::WBP_GraphicsSettings_C_BndEvt__WBP_GraphicsSettings_FOVSlider_1_K2Node_ComponentBoundEvent_30_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_GammaSlider_K2Node_ComponentBoundEvent_26_LostFocusWithDelta__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   NewValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_GammaSlider_K2Node_ComponentBoundEvent_26_LostFocusWithDelta__DelegateSignature(float NewValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_GammaSlider_K2Node_ComponentBoundEvent_26_LostFocusWithDelta__DelegateSignature");

	Params::WBP_GraphicsSettings_C_BndEvt__WBP_GraphicsSettings_GammaSlider_K2Node_ComponentBoundEvent_26_LostFocusWithDelta__DelegateSignature Parms{};

	Parms.NewValue = NewValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_WBP_ConsoleGraphicsModeSelect_K2Node_ComponentBoundEvent_29_Changed__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_WBP_ConsoleGraphicsModeSelect_K2Node_ComponentBoundEvent_29_Changed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_WBP_ConsoleGraphicsModeSelect_K2Node_ComponentBoundEvent_29_Changed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_button_simplefx_K2Node_ComponentBoundEvent_28_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_button_simplefx_K2Node_ComponentBoundEvent_28_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_button_simplefx_K2Node_ComponentBoundEvent_28_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_button_simplelights_K2Node_ComponentBoundEvent_27_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_button_simplelights_K2Node_ComponentBoundEvent_27_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_button_simplelights_K2Node_ComponentBoundEvent_27_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_CamRoll_K2Node_ComponentBoundEvent_25_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_CamRoll_K2Node_ComponentBoundEvent_25_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_CamRoll_K2Node_ComponentBoundEvent_25_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_HDR_Button_K2Node_ComponentBoundEvent_24_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_HDR_Button_K2Node_ComponentBoundEvent_24_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_HDR_Button_K2Node_ComponentBoundEvent_24_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_unlimitedragdolls_K2Node_ComponentBoundEvent_23_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_unlimitedragdolls_K2Node_ComponentBoundEvent_23_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_unlimitedragdolls_K2Node_ComponentBoundEvent_23_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_ScreenShake_K2Node_ComponentBoundEvent_22_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_ScreenShake_K2Node_ComponentBoundEvent_22_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_ScreenShake_K2Node_ComponentBoundEvent_22_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_StuntLines_K2Node_ComponentBoundEvent_21_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_StuntLines_K2Node_ComponentBoundEvent_21_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_StuntLines_K2Node_ComponentBoundEvent_21_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_ReducedViolence_K2Node_ComponentBoundEvent_20_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_ReducedViolence_K2Node_ComponentBoundEvent_20_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_ReducedViolence_K2Node_ComponentBoundEvent_20_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_ResoCombo_1_K2Node_ComponentBoundEvent_11_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_ResoCombo_1_K2Node_ComponentBoundEvent_11_OnSelectionChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_ResoCombo_1_K2Node_ComponentBoundEvent_11_OnSelectionChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.CustomEvent_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EHudColor                               Color                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GraphicsSettings_C::CustomEvent_0(EHudColor Color)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "CustomEvent_0");

	Params::WBP_GraphicsSettings_C_CustomEvent_0 Parms{};

	Parms.Color = Color;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_ssr_K2Node_ComponentBoundEvent_19_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_ssr_K2Node_ComponentBoundEvent_19_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_ssr_K2Node_ComponentBoundEvent_19_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_BLOOM_K2Node_ComponentBoundEvent_18_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_BLOOM_K2Node_ComponentBoundEvent_18_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_BLOOM_K2Node_ComponentBoundEvent_18_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_SimpleSloMo_K2Node_ComponentBoundEvent_17_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_SimpleSloMo_K2Node_ComponentBoundEvent_17_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_SimpleSloMo_K2Node_ComponentBoundEvent_17_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_EnemyOutlines_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_EnemyOutlines_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_EnemyOutlines_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_maxfps_K2Node_ComponentBoundEvent_15_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_maxfps_K2Node_ComponentBoundEvent_15_OnSelectionChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_maxfps_K2Node_ComponentBoundEvent_15_OnSelectionChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_FOVSlider_K2Node_ComponentBoundEvent_14_OnControllerCaptureEndEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_FOVSlider_K2Node_ComponentBoundEvent_14_OnControllerCaptureEndEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_FOVSlider_K2Node_ComponentBoundEvent_14_OnControllerCaptureEndEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_FOVSlider_K2Node_ComponentBoundEvent_13_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_FOVSlider_K2Node_ComponentBoundEvent_13_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_FOVSlider_K2Node_ComponentBoundEvent_13_OnFloatValueChangedEvent__DelegateSignature");

	Params::WBP_GraphicsSettings_C_BndEvt__WBP_GraphicsSettings_FOVSlider_K2Node_ComponentBoundEvent_13_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__WBP_GraphicsSettings_FOVSlider_K2Node_ComponentBoundEvent_12_OnMouseCaptureEndEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__WBP_GraphicsSettings_FOVSlider_K2Node_ComponentBoundEvent_12_OnMouseCaptureEndEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__WBP_GraphicsSettings_FOVSlider_K2Node_ComponentBoundEvent_12_OnMouseCaptureEndEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__ReducedFlash_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__ReducedFlash_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__ReducedFlash_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__RTXREF_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__RTXREF_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__RTXREF_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__VoxelPhysicsToggle_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__VoxelPhysicsToggle_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__VoxelPhysicsToggle_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__shadows_Button_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__shadows_Button_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__shadows_Button_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__ResoCombo_K2Node_ComponentBoundEvent_6_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__ResoCombo_K2Node_ComponentBoundEvent_6_OnSelectionChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__ResoCombo_K2Node_ComponentBoundEvent_6_OnSelectionChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__button_destro_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__button_destro_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__button_destro_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__button_emptyshells_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__button_emptyshells_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__button_emptyshells_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__button_celshade_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__button_celshade_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__button_celshade_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__button_motionblur_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__button_motionblur_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__button_motionblur_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__button_ao_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__button_ao_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__button_ao_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.BndEvt__button_vsync_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_GraphicsSettings_C::BndEvt__button_vsync_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "BndEvt__button_vsync_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_GraphicsSettings_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_GraphicsSettings_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "PreConstruct");

	Params::WBP_GraphicsSettings_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.UpdateDisplay
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_GraphicsSettings_C::UpdateDisplay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "UpdateDisplay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.OnShown
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_GraphicsSettings_C::OnShown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "OnShown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.GatherAndSave
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_GraphicsSettings_C::GatherAndSave()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "GatherAndSave");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.GetDefaultFocus
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget**                         NewParam                                               (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GraphicsSettings_C::GetDefaultFocus(class UWidget** NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "GetDefaultFocus");

	Params::WBP_GraphicsSettings_C_GetDefaultFocus Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.Enter Window Mode Or DlssorAMD
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_GraphicsSettings_C::Enter_Window_Mode_Or_DlssorAMD(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "Enter Window Mode Or DlssorAMD");

	Params::WBP_GraphicsSettings_C_Enter_Window_Mode_Or_DlssorAMD Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.To Reso
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_GraphicsSettings_C::To_Reso(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "To Reso");

	Params::WBP_GraphicsSettings_C_To_Reso Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.To Vsync
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_GraphicsSettings_C::To_Vsync(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "To Vsync");

	Params::WBP_GraphicsSettings_C_To_Vsync Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.UpdateFOVDisplay
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_GraphicsSettings_C::UpdateFOVDisplay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "UpdateFOVDisplay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.GetFPSIndexFromVal
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   FPS                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Index_0                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GraphicsSettings_C::GetFPSIndexFromVal(float FPS, int32* Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "GetFPSIndexFromVal");

	Params::WBP_GraphicsSettings_C_GetFPSIndexFromVal Parms{};

	Parms.FPS = FPS;

	UObject::ProcessEvent(Func, &Parms);

	if (Index_0 != nullptr)
		*Index_0 = Parms.Index_0;
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.OutlineColorSelected
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EHudColor                               NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GraphicsSettings_C::OutlineColorSelected(EHudColor NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "OutlineColorSelected");

	Params::WBP_GraphicsSettings_C_OutlineColorSelected Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.To DLSSOr FOV
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_GraphicsSettings_C::To_DLSSOr_FOV(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "To DLSSOr FOV");

	Params::WBP_GraphicsSettings_C_To_DLSSOr_FOV Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.Nav Through Reflections
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_GraphicsSettings_C::Nav_Through_Reflections(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "Nav Through Reflections");

	Params::WBP_GraphicsSettings_C_Nav_Through_Reflections Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.HandleKeyDown
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// bool*                                   Handled                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_GraphicsSettings_C::HandleKeyDown(const struct FKey& Key, bool* Handled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "HandleKeyDown");

	Params::WBP_GraphicsSettings_C_HandleKeyDown Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);

	if (Handled != nullptr)
		*Handled = Parms.Handled;
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.Left Gamma
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_GraphicsSettings_C::Left_Gamma(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "Left Gamma");

	Params::WBP_GraphicsSettings_C_Left_Gamma Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.Right Gamma
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_GraphicsSettings_C::Right_Gamma(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "Right Gamma");

	Params::WBP_GraphicsSettings_C_Right_Gamma Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.fovoramd
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_GraphicsSettings_C::fovoramd(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "fovoramd");

	Params::WBP_GraphicsSettings_C_fovoramd Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.Enter Window Mode Or Dls
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_GraphicsSettings_C::Enter_Window_Mode_Or_Dls(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "Enter Window Mode Or Dls");

	Params::WBP_GraphicsSettings_C_Enter_Window_Mode_Or_Dls Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.HasOwnerFocusForUser
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   UserIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Value                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_GraphicsSettings_C::HasOwnerFocusForUser(class UWidget* Widget, int32 UserIndex, bool* Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "HasOwnerFocusForUser");

	Params::WBP_GraphicsSettings_C_HasOwnerFocusForUser Parms{};

	Parms.Widget = Widget;
	Parms.UserIndex = UserIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (Value != nullptr)
		*Value = Parms.Value;
}


// Function WBP_GraphicsSettings.WBP_GraphicsSettings_C.HasOwnerFocus
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Value                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_GraphicsSettings_C::HasOwnerFocus(class UWidget* Widget, bool* Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GraphicsSettings_C", "HasOwnerFocus");

	Params::WBP_GraphicsSettings_C_HasOwnerFocus Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);

	if (Value != nullptr)
		*Value = Parms.Value;
}


SDK_NAMESPACE_END
