#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FreshList

#include "Basic.hpp"

#include "WBP_FreshList_classes.hpp"
#include "WBP_FreshList_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_FreshList.WBP_FreshList_C.ExecuteUbergraph_WBP_FreshList
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FreshList_C::ExecuteUbergraph_WBP_FreshList(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FreshList_C", "ExecuteUbergraph_WBP_FreshList");

	Params::WBP_FreshList_C_ExecuteUbergraph_WBP_FreshList Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FreshList.WBP_FreshList_C.OnHov_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EFeat                                   Out                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FreshList_C::OnHov_Event_0(EFeat Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FreshList_C", "OnHov_Event_0");

	Params::WBP_FreshList_C_OnHov_Event_0 Parms{};

	Parms.Out = Out;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FreshList.WBP_FreshList_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_FreshList_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FreshList_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
