#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GraphicsSettings

#include "Basic.hpp"

#include "ThankYouVeryCool_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_GraphicsSettings.WBP_GraphicsSettings_C
// 0x02A8 (0x0508 - 0x0260)
class UWBP_GraphicsSettings_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_AdamSmallToggleButton_C*           Bloom;                                             // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamHUDColor_C*                    Blue;                                              // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           button_ao;                                         // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           button_celshade;                                   // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           button_destro;                                     // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           button_emptyshells;                                // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           button_motionblur;                                 // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           button_simplefx;                                   // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           button_simplelights;                               // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           button_vsync;                                      // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           CamRoll;                                           // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUniformGridPanel*                      ColorGrid;                                         // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             ConsoleGraphicsModeRow;                            // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UStyledComboBoxSetting_C*               DLSS;                                              // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             DLSSRow;                                           // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           EnemyOutlines;                                     // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UStyledComboBoxSetting_C*               FFX;                                               // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             FFXROW;                                            // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             FOVDisplay;                                        // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             FOVDisplay_1;                                      // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                FOVSlider;                                         // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                FOVSlider_1;                                       // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSlider_C*                      GammaSlider;                                       // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamHUDColor_C*                    Green;                                             // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             HandheldFOVRow;                                    // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           HDR_Button;                                        // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             HDRROW;                                            // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_3;                                           // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UStyledComboBoxSetting_C*               MaxFPS;                                            // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           mtd;                                               // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamHUDColor_C*                    Orange;                                            // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamHUDColor_C*                    Red;                                               // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           ReducedFlash;                                      // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           ReducedViolence;                                   // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UStyledComboBoxSetting_C*               ResoCombo;                                         // 0x0390(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           RTXREF;                                            // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             RTXROW;                                            // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           ScreenShake;                                       // 0x03A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamButton_C*                      SettingsReset;                                     // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           shadows_Button;                                    // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           SimpleSloMo;                                       // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           ssr;                                               // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           StuntLines;                                        // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           unlimitedragdolls;                                 // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_117;                                   // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamSmallToggleButton_C*           VoxelPhysicsToggle;                                // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row;                                           // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_1;                                         // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_2;                                         // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_3;                                         // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_4;                                         // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_5;                                         // 0x0418(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_6;                                         // 0x0420(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_7;                                         // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_8;                                         // 0x0430(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_9;                                         // 0x0438(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_10;                                        // 0x0440(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_11;                                        // 0x0448(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_12;                                        // 0x0450(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_13;                                        // 0x0458(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_14;                                        // 0x0460(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_15;                                        // 0x0468(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_16;                                        // 0x0470(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_17;                                        // 0x0478(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_18;                                        // 0x0480(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_19;                                        // 0x0488(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_60;                                        // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_180;                                       // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_296;                                       // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_297;                                       // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_379;                                       // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_543;                                       // 0x04B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_686;                                       // 0x04C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBO_Row_C*                             WBO_Row_774;                                       // 0x04C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ConsoleGraphicsModeSelect_C*       WBP_ConsoleGraphicsModeSelect;                     // 0x04D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamHUDColor_C*                    White;                                             // 0x04D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDefaultRadioSelectSetting_C*           WindowSelection;                                   // 0x04E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidget*                                SelectedWindow;                                    // 0x04E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsSettingUp;                                      // 0x04F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	EHudColor                                     SelectedOutlineColor;                              // 0x04F1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NewVar_0;                                          // 0x04F2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4F3[0x5];                                      // 0x04F3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UUserWidget*>                    WidgetsToHide;                                     // 0x04F8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)

public:
	void ExecuteUbergraph_WBP_GraphicsSettings(int32 EntryPoint);
	void ResetGameSettings();
	void CancelResetSettings();
	void BndEvt__WBP_GraphicsSettings_SettingsReset_K2Node_ComponentBoundEvent_35_OnPressed__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_FFX_K2Node_ComponentBoundEvent_34_OnSelectionChanged__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_unlimitedragdolls_1_K2Node_ComponentBoundEvent_33_OnClicked__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_FOVSlider_1_K2Node_ComponentBoundEvent_32_OnMouseCaptureEndEvent__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_FOVSlider_1_K2Node_ComponentBoundEvent_31_OnControllerCaptureEndEvent__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_FOVSlider_1_K2Node_ComponentBoundEvent_30_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void BndEvt__WBP_GraphicsSettings_GammaSlider_K2Node_ComponentBoundEvent_26_LostFocusWithDelta__DelegateSignature(float NewValue);
	void BndEvt__WBP_GraphicsSettings_WBP_ConsoleGraphicsModeSelect_K2Node_ComponentBoundEvent_29_Changed__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_button_simplefx_K2Node_ComponentBoundEvent_28_OnClicked__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_button_simplelights_K2Node_ComponentBoundEvent_27_OnClicked__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_CamRoll_K2Node_ComponentBoundEvent_25_OnClicked__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_HDR_Button_K2Node_ComponentBoundEvent_24_OnClicked__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_unlimitedragdolls_K2Node_ComponentBoundEvent_23_OnClicked__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_ScreenShake_K2Node_ComponentBoundEvent_22_OnClicked__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_StuntLines_K2Node_ComponentBoundEvent_21_OnClicked__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_ReducedViolence_K2Node_ComponentBoundEvent_20_OnClicked__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_ResoCombo_1_K2Node_ComponentBoundEvent_11_OnSelectionChanged__DelegateSignature();
	void CustomEvent_0(EHudColor Color);
	void BndEvt__WBP_GraphicsSettings_ssr_K2Node_ComponentBoundEvent_19_OnClicked__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_BLOOM_K2Node_ComponentBoundEvent_18_OnClicked__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_SimpleSloMo_K2Node_ComponentBoundEvent_17_OnClicked__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_EnemyOutlines_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_maxfps_K2Node_ComponentBoundEvent_15_OnSelectionChanged__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_FOVSlider_K2Node_ComponentBoundEvent_14_OnControllerCaptureEndEvent__DelegateSignature();
	void BndEvt__WBP_GraphicsSettings_FOVSlider_K2Node_ComponentBoundEvent_13_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void BndEvt__WBP_GraphicsSettings_FOVSlider_K2Node_ComponentBoundEvent_12_OnMouseCaptureEndEvent__DelegateSignature();
	void BndEvt__ReducedFlash_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature();
	void BndEvt__RTXREF_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature();
	void BndEvt__VoxelPhysicsToggle_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature();
	void BndEvt__shadows_Button_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature();
	void BndEvt__ResoCombo_K2Node_ComponentBoundEvent_6_OnSelectionChanged__DelegateSignature();
	void BndEvt__button_destro_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature();
	void BndEvt__button_emptyshells_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature();
	void BndEvt__button_celshade_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature();
	void BndEvt__button_motionblur_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature();
	void BndEvt__button_ao_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature();
	void BndEvt__button_vsync_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void UpdateDisplay();
	void OnShown();
	void GatherAndSave();
	void GetDefaultFocus(class UWidget** NewParam);
	class UWidget* Enter_Window_Mode_Or_DlssorAMD(EUINavigation Navigation_0);
	class UWidget* To_Reso(EUINavigation Navigation_0);
	class UWidget* To_Vsync(EUINavigation Navigation_0);
	void UpdateFOVDisplay();
	void GetFPSIndexFromVal(float FPS, int32* Index_0);
	void OutlineColorSelected(EHudColor NewParam);
	class UWidget* To_DLSSOr_FOV(EUINavigation Navigation_0);
	class UWidget* Nav_Through_Reflections(EUINavigation Navigation_0);
	void HandleKeyDown(const struct FKey& Key, bool* Handled);
	class UWidget* Left_Gamma(EUINavigation Navigation_0);
	class UWidget* Right_Gamma(EUINavigation Navigation_0);
	class UWidget* fovoramd(EUINavigation Navigation_0);
	class UWidget* Enter_Window_Mode_Or_Dls(EUINavigation Navigation_0);
	void HasOwnerFocusForUser(class UWidget* Widget, int32 UserIndex, bool* Value);
	void HasOwnerFocus(class UWidget* Widget, bool* Value);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_GraphicsSettings_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_GraphicsSettings_C")
	}
	static class UWBP_GraphicsSettings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GraphicsSettings_C>();
	}
};
DUMPER7_ASSERTS_UWBP_GraphicsSettings_C;

SDK_NAMESPACE_END
