#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FreshManager

#include "Basic.hpp"

#include "ThankYouVeryCool_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_FreshManager.WBP_FreshManager_C
// 0x0030 (0x0290 - 0x0260)
class UWBP_FreshManager_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UOverlay*                               FreshOverlay;                                      // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          NextFresh;                                         // 0x0270(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	EFeat                                         NextFeat;                                          // 0x0271(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_272[0x2];                                      // 0x0272(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         PreCount;                                          // 0x0274(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<EFeat>                                 FeatQ;                                             // 0x0278(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         TilNext;                                           // 0x0288(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_FreshManager(int32 EntryPoint);
	void OnStatsReset_Event_0();
	void ProcessQue();
	void Construct();
	void ShowFresh(EFeat NewParam);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_FreshManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_FreshManager_C")
	}
	static class UWBP_FreshManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_FreshManager_C>();
	}
};
DUMPER7_ASSERTS_UWBP_FreshManager_C;

SDK_NAMESPACE_END
