#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_XHairSelect

#include "Basic.hpp"

#include "WBP_XHairSelect_classes.hpp"
#include "WBP_XHairSelect_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_XHairSelect.WBP_XHairSelect_C.ExecuteUbergraph_WBP_XHairSelect
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_XHairSelect_C::ExecuteUbergraph_WBP_XHairSelect(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_XHairSelect_C", "ExecuteUbergraph_WBP_XHairSelect");

	Params::WBP_XHairSelect_C_ExecuteUbergraph_WBP_XHairSelect Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_XHairSelect.WBP_XHairSelect_C.BndEvt__WBP_XHairSelect_UIKeyListener_25_K2Node_ComponentBoundEvent_4_UIKeyListenerKeyEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UWBP_XHairSelect_C::BndEvt__WBP_XHairSelect_UIKeyListener_25_K2Node_ComponentBoundEvent_4_UIKeyListenerKeyEvent__DelegateSignature(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_XHairSelect_C", "BndEvt__WBP_XHairSelect_UIKeyListener_25_K2Node_ComponentBoundEvent_4_UIKeyListenerKeyEvent__DelegateSignature");

	Params::WBP_XHairSelect_C_BndEvt__WBP_XHairSelect_UIKeyListener_25_K2Node_ComponentBoundEvent_4_UIKeyListenerKeyEvent__DelegateSignature Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_XHairSelect.WBP_XHairSelect_C.OnPrevious
// (BlueprintCallable, BlueprintEvent)

void UWBP_XHairSelect_C::OnPrevious()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_XHairSelect_C", "OnPrevious");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_XHairSelect.WBP_XHairSelect_C.OnNext
// (BlueprintCallable, BlueprintEvent)

void UWBP_XHairSelect_C::OnNext()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_XHairSelect_C", "OnNext");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_XHairSelect.WBP_XHairSelect_C.BndEvt__WBP_XHairSelect_Fwd_K2Node_ComponentBoundEvent_3_Pressed__DelegateSignature
// (BlueprintEvent)
// Parameters:
// EVoxelEditMod                           OutNav                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_XHairSelect_C::BndEvt__WBP_XHairSelect_Fwd_K2Node_ComponentBoundEvent_3_Pressed__DelegateSignature(EVoxelEditMod OutNav)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_XHairSelect_C", "BndEvt__WBP_XHairSelect_Fwd_K2Node_ComponentBoundEvent_3_Pressed__DelegateSignature");

	Params::WBP_XHairSelect_C_BndEvt__WBP_XHairSelect_Fwd_K2Node_ComponentBoundEvent_3_Pressed__DelegateSignature Parms{};

	Parms.OutNav = OutNav;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_XHairSelect.WBP_XHairSelect_C.BndEvt__WBP_XHairSelect_Back_K2Node_ComponentBoundEvent_2_Pressed__DelegateSignature
// (BlueprintEvent)
// Parameters:
// EVoxelEditMod                           OutNav                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_XHairSelect_C::BndEvt__WBP_XHairSelect_Back_K2Node_ComponentBoundEvent_2_Pressed__DelegateSignature(EVoxelEditMod OutNav)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_XHairSelect_C", "BndEvt__WBP_XHairSelect_Back_K2Node_ComponentBoundEvent_2_Pressed__DelegateSignature");

	Params::WBP_XHairSelect_C_BndEvt__WBP_XHairSelect_Back_K2Node_ComponentBoundEvent_2_Pressed__DelegateSignature Parms{};

	Parms.OutNav = OutNav;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_XHairSelect.WBP_XHairSelect_C.BndEvt__WBP_XHairSelect_WBP_AdamButton_0_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_XHairSelect_C::BndEvt__WBP_XHairSelect_WBP_AdamButton_0_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_XHairSelect_C", "BndEvt__WBP_XHairSelect_WBP_AdamButton_0_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_XHairSelect.WBP_XHairSelect_C.BndEvt__WBP_XHairSelect_WBP_AdamButton_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_XHairSelect_C::BndEvt__WBP_XHairSelect_WBP_AdamButton_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_XHairSelect_C", "BndEvt__WBP_XHairSelect_WBP_AdamButton_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_XHairSelect.WBP_XHairSelect_C.SetForIndex
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_XHairSelect_C::SetForIndex(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_XHairSelect_C", "SetForIndex");

	Params::WBP_XHairSelect_C_SetForIndex Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_XHairSelect.WBP_XHairSelect_C.GetColorAndOpacity_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UWBP_XHairSelect_C::GetColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_XHairSelect_C", "GetColorAndOpacity_0");

	Params::WBP_XHairSelect_C_GetColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_XHairSelect.WBP_XHairSelect_C.HandleKeyDown
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// bool*                                   Handled                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_XHairSelect_C::HandleKeyDown(const struct FKey& Key, bool* Handled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_XHairSelect_C", "HandleKeyDown");

	Params::WBP_XHairSelect_C_HandleKeyDown Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);

	if (Handled != nullptr)
		*Handled = Parms.Handled;
}


SDK_NAMESPACE_END
