#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CmpgnLvl

#include "Basic.hpp"

#include "WBP_CmpgnLvl_classes.hpp"
#include "WBP_CmpgnLvl_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_CmpgnLvl.WBP_CmpgnLvl_C.ExecuteUbergraph_WBP_CmpgnLvl
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CmpgnLvl_C::ExecuteUbergraph_WBP_CmpgnLvl(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CmpgnLvl_C", "ExecuteUbergraph_WBP_CmpgnLvl");

	Params::WBP_CmpgnLvl_C_ExecuteUbergraph_WBP_CmpgnLvl Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CmpgnLvl.WBP_CmpgnLvl_C.Load
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<class FString>&            NewParam                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_CmpgnLvl_C::Load(const TArray<class FString>& NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CmpgnLvl_C", "Load");

	Params::WBP_CmpgnLvl_C_Load Parms{};

	Parms.NewParam = std::move(NewParam);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CmpgnLvl.WBP_CmpgnLvl_C.BndEvt__WBP_CmpgnLvl_UseSS_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_CmpgnLvl_C::BndEvt__WBP_CmpgnLvl_UseSS_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CmpgnLvl_C", "BndEvt__WBP_CmpgnLvl_UseSS_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CmpgnLvl.WBP_CmpgnLvl_C.BndEvt__WBP_CmpgnLvl_WBP_AdamButton_Icon_3_K2Node_ComponentBoundEvent_3_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_CmpgnLvl_C::BndEvt__WBP_CmpgnLvl_WBP_AdamButton_Icon_3_K2Node_ComponentBoundEvent_3_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CmpgnLvl_C", "BndEvt__WBP_CmpgnLvl_WBP_AdamButton_Icon_3_K2Node_ComponentBoundEvent_3_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CmpgnLvl.WBP_CmpgnLvl_C.BndEvt__WBP_CmpgnLvl_WBP_AdamButton_Icon_1_K2Node_ComponentBoundEvent_2_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_CmpgnLvl_C::BndEvt__WBP_CmpgnLvl_WBP_AdamButton_Icon_1_K2Node_ComponentBoundEvent_2_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CmpgnLvl_C", "BndEvt__WBP_CmpgnLvl_WBP_AdamButton_Icon_1_K2Node_ComponentBoundEvent_2_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CmpgnLvl.WBP_CmpgnLvl_C.BndEvt__WBP_CmpgnLvl_WBP_AdamButton_Icon_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_CmpgnLvl_C::BndEvt__WBP_CmpgnLvl_WBP_AdamButton_Icon_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CmpgnLvl_C", "BndEvt__WBP_CmpgnLvl_WBP_AdamButton_Icon_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CmpgnLvl.WBP_CmpgnLvl_C.BndEvt__WBP_CmpgnLvl_WBP_AdamButton_Icon_2_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature
// (BlueprintEvent)

void UWBP_CmpgnLvl_C::BndEvt__WBP_CmpgnLvl_WBP_AdamButton_Icon_2_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CmpgnLvl_C", "BndEvt__WBP_CmpgnLvl_WBP_AdamButton_Icon_2_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CmpgnLvl.WBP_CmpgnLvl_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CmpgnLvl_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CmpgnLvl_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CmpgnLvl.WBP_CmpgnLvl_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_CmpgnLvl_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CmpgnLvl_C", "PreConstruct");

	Params::WBP_CmpgnLvl_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CmpgnLvl.WBP_CmpgnLvl_C.GetLvlInfo
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UArcadeLevelAsset**               OutLvl                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FCustomCampaignText*             OutTet                                                 (Parm, OutParm)

void UWBP_CmpgnLvl_C::GetLvlInfo(class UArcadeLevelAsset** OutLvl, struct FCustomCampaignText* OutTet)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CmpgnLvl_C", "GetLvlInfo");

	Params::WBP_CmpgnLvl_C_GetLvlInfo Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutLvl != nullptr)
		*OutLvl = Parms.OutLvl;

	if (OutTet != nullptr)
		*OutTet = std::move(Parms.OutTet);
}


// Function WBP_CmpgnLvl.WBP_CmpgnLvl_C.SetUseScreen
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_CmpgnLvl_C::SetUseScreen(bool NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CmpgnLvl_C", "SetUseScreen");

	Params::WBP_CmpgnLvl_C_SetUseScreen Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
