#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GibFeedback

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_GibFeedback.WBP_GibFeedback_C
// 0x0018 (0x0278 - 0x0260)
class UWBP_GibFeedback_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_118;                                         // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AdamButton_C*                      WBP_AdamButton;                                    // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_GibFeedback(int32 EntryPoint);
	void BndEvt__WBP_WishlistPlz_WBP_AdamButton_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_GibFeedback_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_GibFeedback_C")
	}
	static class UWBP_GibFeedback_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GibFeedback_C>();
	}
};
DUMPER7_ASSERTS_UWBP_GibFeedback_C;

SDK_NAMESPACE_END
